services:
  db:
    image: postgres:16
    container_name: pg-plataforma
    environment:
      POSTGRES_DB: plataforma_programadores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
